# Generated by Django 4.2.6 on 2023-10-30 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성시간"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정됨")),
                (
                    "title",
                    models.CharField(default="", max_length=200, verbose_name="제목"),
                ),
                ("photo", models.URLField(default="", null=True, verbose_name="사진파일")),
                ("description", models.TextField(blank=True, verbose_name="내용")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
