# Generated by Django 4.2.6 on 2023-10-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
