# Generated by Django 4.2.6 on 2023-10-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="is_approved",
            field=models.CharField(
                choices=[
                    ("approval", "승인"),
                    ("disapproval", "미승인"),
                    ("under_review", "검토중"),
                ],
                default="under_review",
                max_length=15,
            ),
        ),
    ]
