# Generated by Django 4.2.6 on 2023-10-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="photo_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="photo",
            field=models.FileField(
                default="", null=True, upload_to="photos/", verbose_name="사진파일"
            ),
        ),
    ]
