# Generated by Django 4.2.6 on 2023-10-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("approval", "승인"),
                            ("disapproval", "미승인"),
                            ("under_review", "검토중"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
